# Generated by Django 5.2 on 2025-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_moodentry_energy_moodentry_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='journal_entry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
