# Generated by Django 5.2 on 2025-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_studygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygoal',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='studygoal',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
