# Generated by Django 5.2 on 2025-05-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_remove_studygoal_created_at_alter_studygoal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygoal',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
