# Generated by Django 5.1.2 on 2025-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_drawing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='image_data',
            new_name='image_base64',
        ),
        migrations.AddField(
            model_name='drawing',
            name='query',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
