# Generated by Django 5.1.2 on 2025-06-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_drawing_query_alter_drawing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('😃 Happy', '😃 Happy'), ('😢 Sad', '😢 Sad'), ('😡 Angry', '😡 Angry'), ('😴 Tired', '😴 Tired'), ('😌 Relaxed', '😌 Relaxed'), ('😰 Anxious', '😰 Anxious'), ('🤩 Excited', '🤩 Excited')], max_length=20),
        ),
    ]
